# AppVeyor build configuration

branches:
  except:
  - master

environment:
  matrix:
   - platform: x86
   - platform: x64

# Build script
build_script:
- git submodule update --init
- powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Platform %platform%

# Publish artifacts (installer and portable zip)
artifacts:
 - path: build-*/Release/PicoTorrent-*-*.exe
 - path: build-*/Release/PicoTorrent-*-*.zip

test: off
