name: CI
on:
  pull_request:
  push:
    branches:
      - feature/**
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x86, x64]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git fetch --prune --unshallow
          git submodule update --init --recursive

      - name: Setup vcpkg
        run: .\vendor\vcpkg\bootstrap-vcpkg.bat

      - name: Install vcpkg ports
        run: |
          .\vendor\vcpkg\vcpkg.exe install boost-log:${{ matrix.arch }}-windows-static-md
          .\vendor\vcpkg\vcpkg.exe install fmt:${{ matrix.arch }}-windows-static-md
          .\vendor\vcpkg\vcpkg.exe install libtorrent:${{ matrix.arch }}-windows-static-md
          .\vendor\vcpkg\vcpkg.exe install nlohmann-json:${{ matrix.arch }}-windows-static-md
          .\vendor\vcpkg\vcpkg.exe install sqlite3:${{ matrix.arch }}-windows-static-md

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Build
        run: dotnet cake --platform=${{ matrix.arch }} --target=Publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PicoTorrent-${{ matrix.arch }}-CI-binaries
          path: |
            build-${{ matrix.arch }}/Release/packages/PicoTorrent-*-${{ matrix.arch }}.exe
            build-${{ matrix.arch }}/Release/packages/PicoTorrent-*-${{ matrix.arch }}.zip
            build-${{ matrix.arch }}/Release/packages/PicoTorrent-*-${{ matrix.arch }}.symbols.zip
